### ISSUE TITLE
Ques about ablation

### ISSUE THREAD

**Issue by huixiancheng** [StiphyJay/FastPillars#7]
How much improvement will be gained by switching centerpoint's backbone from original structure to CSPRepVGG or CSPRep-Res34?
```
    neck=dict(
        type="RPN",
        layer_nums=[3, 5, 5],
        ds_layer_strides=[2, 2, 2],
        ds_num_filters=[64, 128, 256],
        us_layer_strides=[0.5, 1, 2],
        us_num_filters=[128, 128, 128],
        num_input_features=64,
        logger=logging.getLogger("RPN"),
    ),
```

**Comment by StiphyJay** [comment]
Sorry for the late reply. We didn't conduct this ablation experiment because there are many different variables compared to the original CenterPoint. For example, CenterPoint-Voxel is a voxel-based backbone using spconv3d, while we are a pillar-based backbone using dense conv2d. Besides, CenterPoint-Voxel adopts voxel-feature-encoder (VFE), while we use pillar-feature-encoder (PFE). Additionally, our neck module is also different. Please refer to our paper for more details.

**Comment by huixiancheng** [comment]
Hi, thx for u reply. Maybe we have different views on details. 
Assuming the code are based on det3d framework, compare with official [centerpoint cfg](https://github.com/VISION-SJTU/PillarNet-LTS/blob/master/configs/pillarnet/pillarnet_centerhead_nusc.py), the diff are from reader (diff PFE) and neck (diff backbone and real neck?). If I'm not mistaken.
However, for the 3 contributes: 
1.  MAFE gain 0.6 map improvement.
2. The backbone and neck, if we consider it as one model, from Tab.2, it bring almost 10 map improvement, compare with CP-PointPillars.
![image](https://github.com/StiphyJay/FastPillars/assets/65054204/c4c30121-e24a-4fe5-9a27-6831ad298a9d)

I'm confuse about the result, since you use the dense structure in PillarNet's sparse frame.
So, how many map is gained from powerful 2D Dense CNN Backbone? How many map is gained from neck (2x of pontpillar, 8x for pillarnet and yours)? However, the high degree of structural coupling makes it difficult to quantify the differences.

**Comment by StiphyJay** [comment]
Thanks for your attention!

(1). Our code is built based on PillarNet. PillarNet is our baseline. Compared to the PillarNet, our differences come from two aspects: 1. The design of MAPE module, 2. The design of the dense CNN backbone. For the neck and head, which is the same as PillarNet. Because our motivation is to design a deployment-friendly 3D detector, we redesigned the PFE and the SPConv-based backbone in PillarNet. 

(2). Taking FastPillars-m as an example, compared to Pillarnet, only replace their SPConv-based backbone with our dense backbone design (CSPRep-Res34 in FastPillars-m), bringing ~1.0 map improvement on nuScenes dataset.

(3). After replacing the SPConv-based backbone with our dense backbone design (CSPRep-Res34), compared to directly using the PFE design in the PillarNet, our MAPE module can bring ~0.6 map improvement on nuScenes dataset. Therefore, the final performance of FastPillars-m is ~1.6 map higher than PillarNet-34.

(4) For latency, we adopt TensortRT with FP16 for measurement due to the deployment-friendly nature of FastPillars.

(5). The updated version of the manuscript is under review, and we will release the latest version of paper and code soon.

Hope to solve your doubts.

**Comment by huixiancheng** [comment]
Thx for you kind reply.
